/*
 * Tests for mweb_kernel_sig_hash and mweb_sign_kernel_with_ek.
 *
 * Hash vectors generated by calling ltcsuite's MwebKernel.MessageHash().
 * Signing vectors generated by calling ltcsuite's signing path with
 * pinned e_k values (via tools/gen_mweb_fixtures/main.go).
 */
#include "mweb_kernel.h"
#include "mweb_scalar.h"
#include "fixtures/kernel_hash_vectors.h"
#include "fixtures/kernel_sign_vectors.h"

#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#include <wally_core.h>
#include <wally_map.h>

static int failures = 0;
static int test_count = 0;

#define PASS(name) do { test_count++; printf("PASS: %s\n", name); } while (0)
#define FAIL(name, ...) do { test_count++; failures++; printf("FAIL: %s — ", name); printf(__VA_ARGS__); printf("\n"); } while (0)

static void check_hash(const char *name,
                        uint8_t features,
                        const uint8_t excess[33],
                        uint64_t fee, bool has_fee,
                        uint64_t pegin, bool has_pegin,
                        const struct wally_map *pegouts,
                        uint32_t lock_ht, bool has_lock_ht,
                        const uint8_t *stealth,
                        const uint8_t *extra, size_t extra_len,
                        const uint8_t expected[32])
{
    uint8_t got[32];
    if (!mweb_kernel_sig_hash(features, excess,
                              fee, has_fee,
                              pegin, has_pegin,
                              pegouts,
                              lock_ht, has_lock_ht,
                              stealth, extra, extra_len,
                              got)) {
        FAIL(name, "mweb_kernel_sig_hash returned false");
        return;
    }
    if (memcmp(got, expected, 32) != 0) {
        FAIL(name, "hash mismatch");
        printf("  got:  ");
        for (int i = 0; i < 32; i++) printf("%02x", got[i]);
        printf("\n  want: ");
        for (int i = 0; i < 32; i++) printf("%02x", expected[i]);
        printf("\n");
        return;
    }
    PASS(name);
}

/* Build a pegout map value for PSBT:
 * le64(amount) || compact_size(script_len) || script_bytes */
static uint8_t *build_pegout_value(uint64_t amount,
                                    const uint8_t *script, size_t script_len,
                                    size_t *out_len)
{
    uint8_t vi[9];
    size_t vi_len;

    /* le64 amount (8 bytes) */
    uint8_t amt_le[8];
    for (int i = 0; i < 8; i++) amt_le[i] = (uint8_t)(amount >> (i * 8));

    /* compact-size script_len */
    if (script_len < 0xfd) {
        vi[0] = (uint8_t)script_len;
        vi_len = 1;
    } else if (script_len <= 0xffff) {
        vi[0] = 0xfd;
        vi[1] = (uint8_t)(script_len);
        vi[2] = (uint8_t)(script_len >> 8);
        vi_len = 3;
    } else {
        vi[0] = 0xfe;
        vi[1] = (uint8_t)(script_len);
        vi[2] = (uint8_t)(script_len >> 8);
        vi[3] = (uint8_t)(script_len >> 16);
        vi[4] = (uint8_t)(script_len >> 24);
        vi_len = 5;
    }

    *out_len = 8 + vi_len + script_len;
    uint8_t *buf = malloc(*out_len);
    memcpy(buf, amt_le, 8);
    memcpy(buf + 8, vi, vi_len);
    memcpy(buf + 8 + vi_len, script, script_len);
    return buf;
}

static const uint8_t EXCESS[33] = {
    0x08,
    0xa1, 0xa1, 0xa1, 0xa1, 0xa1, 0xa1, 0xa1, 0xa1,
    0xa1, 0xa1, 0xa1, 0xa1, 0xa1, 0xa1, 0xa1, 0xa1,
    0xa1, 0xa1, 0xa1, 0xa1, 0xa1, 0xa1, 0xa1, 0xa1,
    0xa1, 0xa1, 0xa1, 0xa1, 0xa1, 0xa1, 0xa1, 0xa1
};

static const uint8_t STEALTH_EXCESS[33] = {
    0x02,
    0xb2, 0xb2, 0xb2, 0xb2, 0xb2, 0xb2, 0xb2, 0xb2,
    0xb2, 0xb2, 0xb2, 0xb2, 0xb2, 0xb2, 0xb2, 0xb2,
    0xb2, 0xb2, 0xb2, 0xb2, 0xb2, 0xb2, 0xb2, 0xb2,
    0xb2, 0xb2, 0xb2, 0xb2, 0xb2, 0xb2, 0xb2, 0xb2
};

/* P2WPKH script: OP_0 OP_PUSH20 <20-byte hash> */
static const uint8_t PEGOUT_SCRIPT_1[] = {
    0x00, 0x14,
    0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3,
    0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3,
    0xc3, 0xc3, 0xc3, 0xc3
};

/* P2WPKH script for ALL_FEATURES vector pegout 0 */
static const uint8_t PEGOUT_SCRIPT_ALL_0[] = {
    0x00, 0x14,
    0xd4, 0xd4, 0xd4, 0xd4, 0xd4, 0xd4, 0xd4, 0xd4,
    0xd4, 0xd4, 0xd4, 0xd4, 0xd4, 0xd4, 0xd4, 0xd4,
    0xd4, 0xd4, 0xd4, 0xd4
};

/* P2PKH script for ALL_FEATURES vector pegout 1 */
static const uint8_t PEGOUT_SCRIPT_ALL_1[] = {
    0x76, 0xa9, 0x14,
    0xe5, 0xe5, 0xe5, 0xe5, 0xe5, 0xe5, 0xe5, 0xe5,
    0xe5, 0xe5, 0xe5, 0xe5, 0xe5, 0xe5, 0xe5, 0xe5,
    0xe5, 0xe5, 0xe5, 0xe5,
    0x88, 0xac
};

static const uint8_t EXTRA_DATA[] = { 0xde, 0xad, 0xbe, 0xef };

int main(void)
{
    /* 1. FEE_ONLY: features=0x01, fee=50000 */
    check_hash("FEE_ONLY",
               MWEB_KERNEL_FEE_BIT, EXCESS,
               50000, true,
               0, false,
               NULL,
               0, false,
               NULL, NULL, 0,
               KERNEL_HASH_FEE_ONLY);

    /* 2. FEE_AND_PEGIN: features=0x03, fee=10000, pegin=100000000 */
    check_hash("FEE_AND_PEGIN",
               MWEB_KERNEL_FEE_BIT | MWEB_KERNEL_PEGIN_BIT, EXCESS,
               10000, true,
               100000000, true,
               NULL,
               0, false,
               NULL, NULL, 0,
               KERNEL_HASH_FEE_AND_PEGIN);

    /* 3. FEE_AND_STEALTH: features=0x11, fee=25000 */
    check_hash("FEE_AND_STEALTH",
               MWEB_KERNEL_FEE_BIT | MWEB_KERNEL_STEALTH_EXCESS_BIT, EXCESS,
               25000, true,
               0, false,
               NULL,
               0, false,
               STEALTH_EXCESS, NULL, 0,
               KERNEL_HASH_FEE_AND_STEALTH);

    /* 4. FEE_AND_LOCKHEIGHT: features=0x09, fee=30000, lock_height=800000 */
    check_hash("FEE_AND_LOCKHEIGHT",
               MWEB_KERNEL_FEE_BIT | MWEB_KERNEL_HEIGHT_LOCK_BIT, EXCESS,
               30000, true,
               0, false,
               NULL,
               800000, true,
               NULL, NULL, 0,
               KERNEL_HASH_FEE_AND_LOCKHEIGHT);

    /* 5. FEE_AND_PEGOUT: features=0x05, fee=40000, 1 pegout */
    {
        struct wally_map pegout_map;
        wally_map_init(1, NULL, &pegout_map);

        size_t pval_len;
        uint8_t *pval = build_pegout_value(200000000,
                                           PEGOUT_SCRIPT_1, sizeof(PEGOUT_SCRIPT_1),
                                           &pval_len);
        uint8_t key0 = 0x00;
        wally_map_add(&pegout_map, &key0, 1, pval, pval_len);
        free(pval);

        check_hash("FEE_AND_PEGOUT",
                   MWEB_KERNEL_FEE_BIT | MWEB_KERNEL_PEGOUT_BIT, EXCESS,
                   40000, true,
                   0, false,
                   &pegout_map,
                   0, false,
                   NULL, NULL, 0,
                   KERNEL_HASH_FEE_AND_PEGOUT);

        wally_map_clear(&pegout_map);
    }

    /* 6. ALL_FEATURES: features=0x3f, 2 pegouts, stealth, extra_data */
    {
        struct wally_map pegout_map;
        wally_map_init(2, NULL, &pegout_map);

        size_t pval0_len, pval1_len;
        uint8_t *pval0 = build_pegout_value(100000000,
                                            PEGOUT_SCRIPT_ALL_0, sizeof(PEGOUT_SCRIPT_ALL_0),
                                            &pval0_len);
        uint8_t *pval1 = build_pegout_value(50000000,
                                            PEGOUT_SCRIPT_ALL_1, sizeof(PEGOUT_SCRIPT_ALL_1),
                                            &pval1_len);
        uint8_t key0 = 0x00, key1 = 0x01;
        wally_map_add(&pegout_map, &key0, 1, pval0, pval0_len);
        wally_map_add(&pegout_map, &key1, 1, pval1, pval1_len);
        free(pval0);
        free(pval1);

        check_hash("ALL_FEATURES",
                   MWEB_KERNEL_ALL_BITS, EXCESS,
                   15000, true,
                   500000000, true,
                   &pegout_map,
                   900000, true,
                   STEALTH_EXCESS,
                   EXTRA_DATA, sizeof(EXTRA_DATA),
                   KERNEL_HASH_ALL_FEATURES);

        wally_map_clear(&pegout_map);
    }

    /* 7. FEE_ZERO: features=0x01, fee=0 (presence-not-nonzero) */
    check_hash("FEE_ZERO",
               MWEB_KERNEL_FEE_BIT, EXCESS,
               0, true,
               0, false,
               NULL,
               0, false,
               NULL, NULL, 0,
               KERNEL_HASH_FEE_ZERO);

    /* 8. EXTRA_DATA_EMPTY: features=0x21, fee=5000, extra_data=[] */
    check_hash("EXTRA_DATA_EMPTY",
               MWEB_KERNEL_FEE_BIT | MWEB_KERNEL_EXTRA_DATA_BIT, EXCESS,
               5000, true,
               0, false,
               NULL,
               0, false,
               NULL, NULL, 0,
               KERNEL_HASH_EXTRA_DATA_EMPTY);

    /* 9. PLAIN_NO_FEATURES: features=0x00 */
    check_hash("PLAIN_NO_FEATURES",
               0, EXCESS,
               0, false,
               0, false,
               NULL,
               0, false,
               NULL, NULL, 0,
               KERNEL_HASH_PLAIN_NO_FEATURES);

    /* 9. Negative: NULL excess_commitment → false */
    {
        uint8_t dummy[32];
        if (mweb_kernel_sig_hash(0x01, NULL,
                                 50000, true,
                                 0, false,
                                 NULL, 0, false,
                                 NULL, NULL, 0, dummy)) {
            FAIL("NULL_EXCESS", "should have returned false");
        } else {
            PASS("NULL_EXCESS rejected");
        }
    }

    /* ── Kernel signing tests ────────────────────────────────────────── */

    /* 11. SIMPLE: non-stealth signing vector */
    {
        static const uint8_t IN_BLIND[32] = {
            0x05,0x05,0x05,0x05,0x05,0x05,0x05,0x05,
            0x05,0x05,0x05,0x05,0x05,0x05,0x05,0x05,
            0x05,0x05,0x05,0x05,0x05,0x05,0x05,0x05,
            0x05,0x05,0x05,0x05,0x05,0x05,0x05,0x05,
        };
        static const uint8_t IN_TWEAK[32] = {
            0x06,0x06,0x06,0x06,0x06,0x06,0x06,0x06,
            0x06,0x06,0x06,0x06,0x06,0x06,0x06,0x06,
            0x06,0x06,0x06,0x06,0x06,0x06,0x06,0x06,
            0x06,0x06,0x06,0x06,0x06,0x06,0x06,0x06,
        };
        static const uint8_t OUT_BLIND[32] = {
            0x07,0x07,0x07,0x07,0x07,0x07,0x07,0x07,
            0x07,0x07,0x07,0x07,0x07,0x07,0x07,0x07,
            0x07,0x07,0x07,0x07,0x07,0x07,0x07,0x07,
            0x07,0x07,0x07,0x07,0x07,0x07,0x07,0x07,
        };
        static const uint8_t RECV_TX_OFF[32] = {
            0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,
            0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,
            0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,
            0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,
        };
        static const uint8_t RECV_ST_OFF[32] = {
            0x04,0x04,0x04,0x04,0x04,0x04,0x04,0x04,
            0x04,0x04,0x04,0x04,0x04,0x04,0x04,0x04,
            0x04,0x04,0x04,0x04,0x04,0x04,0x04,0x04,
            0x04,0x04,0x04,0x04,0x04,0x04,0x04,0x04,
        };

        mweb_input_ctx_t inp;
        inp.value = 100010000;
        memcpy(inp.blind, IN_BLIND, 32);
        memcpy(inp.stealth_tweak, IN_TWEAK, 32);

        mweb_output_ctx_t outp;
        outp.value = 100000000;
        memcpy(outp.blind, OUT_BLIND, 32);

        struct mweb_kernel_sign_params params;
        memset(&params, 0, sizeof(params));
        params.inputs = &inp;
        params.n_inputs = 1;
        params.outputs = &outp;
        params.n_outputs = 1;
        params.features = MWEB_KERNEL_FEE_BIT;
        params.fee = 10000;
        params.has_fee = true;
        params.received_tx_offset = RECV_TX_OFF;
        params.received_stealth_offset = RECV_ST_OFF;

        struct mweb_kernel_sign_outputs result;
        mweb_err_t err = mweb_sign_kernel_with_ek(KSIGN_EK_SIMPLE, &params, &result);
        if (err != MWEB_OK) {
            FAIL("SIGN_SIMPLE", "returned error %d", err);
        } else if (memcmp(result.excess_kG, KSIGN_EXCESS_SIMPLE, 33) != 0) {
            FAIL("SIGN_SIMPLE", "excess mismatch");
        } else if (memcmp(result.signature, KSIGN_SIG_SIMPLE, 64) != 0) {
            FAIL("SIGN_SIMPLE", "signature mismatch");
        } else if (memcmp(result.tx_offset_final, KSIGN_TX_OFFSET_SIMPLE, 32) != 0) {
            FAIL("SIGN_SIMPLE", "tx_offset mismatch");
        } else if (memcmp(result.stealth_offset_final, KSIGN_STEALTH_OFFSET_SIMPLE, 32) != 0) {
            FAIL("SIGN_SIMPLE", "stealth_offset mismatch");
        } else {
            PASS("SIGN_SIMPLE");
        }
    }

    /* 12. STEALTH: signing vector with stealth-excess tweak */
    {
        static const uint8_t STEALTH_KEY[32] = {
            0x2c,0x2c,0x2c,0x2c,0x2c,0x2c,0x2c,0x2c,
            0x2c,0x2c,0x2c,0x2c,0x2c,0x2c,0x2c,0x2c,
            0x2c,0x2c,0x2c,0x2c,0x2c,0x2c,0x2c,0x2c,
            0x2c,0x2c,0x2c,0x2c,0x2c,0x2c,0x2c,0x2c,
        };
        static const uint8_t IN_BLIND[32] = {
            0x05,0x05,0x05,0x05,0x05,0x05,0x05,0x05,
            0x05,0x05,0x05,0x05,0x05,0x05,0x05,0x05,
            0x05,0x05,0x05,0x05,0x05,0x05,0x05,0x05,
            0x05,0x05,0x05,0x05,0x05,0x05,0x05,0x05,
        };
        static const uint8_t IN_TWEAK[32] = {
            0x06,0x06,0x06,0x06,0x06,0x06,0x06,0x06,
            0x06,0x06,0x06,0x06,0x06,0x06,0x06,0x06,
            0x06,0x06,0x06,0x06,0x06,0x06,0x06,0x06,
            0x06,0x06,0x06,0x06,0x06,0x06,0x06,0x06,
        };
        static const uint8_t OUT_BLIND[32] = {
            0x07,0x07,0x07,0x07,0x07,0x07,0x07,0x07,
            0x07,0x07,0x07,0x07,0x07,0x07,0x07,0x07,
            0x07,0x07,0x07,0x07,0x07,0x07,0x07,0x07,
            0x07,0x07,0x07,0x07,0x07,0x07,0x07,0x07,
        };
        static const uint8_t RECV_TX_OFF[32] = {
            0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,
            0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,
            0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,
            0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,
        };
        static const uint8_t RECV_ST_OFF[32] = {
            0x04,0x04,0x04,0x04,0x04,0x04,0x04,0x04,
            0x04,0x04,0x04,0x04,0x04,0x04,0x04,0x04,
            0x04,0x04,0x04,0x04,0x04,0x04,0x04,0x04,
            0x04,0x04,0x04,0x04,0x04,0x04,0x04,0x04,
        };

        mweb_input_ctx_t inp;
        inp.value = 100005000;
        memcpy(inp.blind, IN_BLIND, 32);
        memcpy(inp.stealth_tweak, IN_TWEAK, 32);

        mweb_output_ctx_t outp;
        outp.value = 100000000;
        memcpy(outp.blind, OUT_BLIND, 32);

        struct mweb_kernel_sign_params params;
        memset(&params, 0, sizeof(params));
        params.inputs = &inp;
        params.n_inputs = 1;
        params.outputs = &outp;
        params.n_outputs = 1;
        params.features = MWEB_KERNEL_FEE_BIT | MWEB_KERNEL_STEALTH_EXCESS_BIT;
        params.fee = 5000;
        params.has_fee = true;
        params.stealth_key_or_null = STEALTH_KEY;
        params.received_tx_offset = RECV_TX_OFF;
        params.received_stealth_offset = RECV_ST_OFF;

        struct mweb_kernel_sign_outputs result;
        mweb_err_t err = mweb_sign_kernel_with_ek(KSIGN_EK_STEALTH, &params, &result);
        if (err != MWEB_OK) {
            FAIL("SIGN_STEALTH", "returned error %d", err);
        } else if (memcmp(result.excess_kG, KSIGN_EXCESS_STEALTH, 33) != 0) {
            FAIL("SIGN_STEALTH", "excess mismatch");
        } else if (memcmp(result.stealth_excess_G, KSIGN_STEALTH_EXCESS_STEALTH, 33) != 0) {
            FAIL("SIGN_STEALTH", "stealth_excess mismatch");
        } else if (memcmp(result.signature, KSIGN_SIG_STEALTH, 64) != 0) {
            FAIL("SIGN_STEALTH", "signature mismatch");
        } else if (memcmp(result.tx_offset_final, KSIGN_TX_OFFSET_STEALTH, 32) != 0) {
            FAIL("SIGN_STEALTH", "tx_offset mismatch");
        } else if (memcmp(result.stealth_offset_final, KSIGN_STEALTH_OFFSET_STEALTH, 32) != 0) {
            FAIL("SIGN_STEALTH", "stealth_offset mismatch");
        } else {
            PASS("SIGN_STEALTH");
        }
    }

    /* ── Negative tests ───────────────────────────────────────────────── */

    /* 13. Unbalanced u64 → MWEB_ERR_BALANCE_FAIL */
    {
        mweb_input_ctx_t inp = { .value = 1000 };
        mweb_output_ctx_t outp = { .value = 2000 };  /* output > input */
        static const uint8_t EK[32] = {0x01};
        static const uint8_t ZERO[32] = {0};
        struct mweb_kernel_sign_params params;
        memset(&params, 0, sizeof(params));
        params.inputs = &inp; params.n_inputs = 1;
        params.outputs = &outp; params.n_outputs = 1;
        params.features = MWEB_KERNEL_FEE_BIT;
        params.fee = 500; params.has_fee = true;
        params.received_tx_offset = ZERO;
        params.received_stealth_offset = ZERO;

        struct mweb_kernel_sign_outputs result;
        mweb_err_t err = mweb_sign_kernel_with_ek(EK, &params, &result);
        if (err == MWEB_ERR_BALANCE_FAIL) {
            PASS("UNBALANCED_REJECTED");
        } else {
            FAIL("UNBALANCED_REJECTED", "expected BALANCE_FAIL, got %d", err);
        }
    }

    /* 14. u64 overflow → MWEB_ERR_BALANCE_FAIL */
    {
        mweb_input_ctx_t inp = { .value = UINT64_MAX };
        mweb_output_ctx_t outp = { .value = UINT64_MAX - 1 };
        static const uint8_t EK[32] = {0x01};
        static const uint8_t ZERO[32] = {0};
        struct mweb_kernel_sign_params params;
        memset(&params, 0, sizeof(params));
        params.inputs = &inp; params.n_inputs = 1;
        params.outputs = &outp; params.n_outputs = 1;
        params.features = MWEB_KERNEL_FEE_BIT | MWEB_KERNEL_PEGIN_BIT;
        params.fee = 1; params.has_fee = true;
        params.pegin_amount = UINT64_MAX; params.has_pegin_amount = true;
        params.received_tx_offset = ZERO;
        params.received_stealth_offset = ZERO;

        struct mweb_kernel_sign_outputs result;
        mweb_err_t err = mweb_sign_kernel_with_ek(EK, &params, &result);
        if (err == MWEB_ERR_BALANCE_FAIL) {
            PASS("OVERFLOW_REJECTED");
        } else {
            FAIL("OVERFLOW_REJECTED", "expected BALANCE_FAIL, got %d", err);
        }
    }

    /* 15. Zero e_k → MWEB_ERR_INVALID_PRESIGN_SCALAR */
    {
        static const uint8_t ZERO_EK[32] = {0};
        static const uint8_t ZERO[32] = {0};
        mweb_input_ctx_t inp = { .value = 1000 };
        mweb_output_ctx_t outp = { .value = 500 };
        struct mweb_kernel_sign_params params;
        memset(&params, 0, sizeof(params));
        params.inputs = &inp; params.n_inputs = 1;
        params.outputs = &outp; params.n_outputs = 1;
        params.features = MWEB_KERNEL_FEE_BIT;
        params.fee = 500; params.has_fee = true;
        params.received_tx_offset = ZERO;
        params.received_stealth_offset = ZERO;

        struct mweb_kernel_sign_outputs result;
        mweb_err_t err = mweb_sign_kernel_with_ek(ZERO_EK, &params, &result);
        if (err == MWEB_ERR_INVALID_PRESIGN_SCALAR) {
            PASS("ZERO_EK_REJECTED");
        } else {
            FAIL("ZERO_EK_REJECTED", "expected INVALID_PRESIGN_SCALAR, got %d", err);
        }
    }

    /* 16. e_k >= n → MWEB_ERR_INVALID_PRESIGN_SCALAR */
    {
        /* secp256k1 order n */
        static const uint8_t ORDER_EK[32] = {
            0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,
            0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFE,
            0xBA,0xAE,0xDC,0xE6,0xAF,0x48,0xA0,0x3B,
            0xBF,0xD2,0x5E,0x8C,0xD0,0x36,0x41,0x41,
        };
        static const uint8_t ZERO[32] = {0};
        mweb_input_ctx_t inp = { .value = 1000 };
        mweb_output_ctx_t outp = { .value = 500 };
        struct mweb_kernel_sign_params params;
        memset(&params, 0, sizeof(params));
        params.inputs = &inp; params.n_inputs = 1;
        params.outputs = &outp; params.n_outputs = 1;
        params.features = MWEB_KERNEL_FEE_BIT;
        params.fee = 500; params.has_fee = true;
        params.received_tx_offset = ZERO;
        params.received_stealth_offset = ZERO;

        struct mweb_kernel_sign_outputs result;
        mweb_err_t err = mweb_sign_kernel_with_ek(ORDER_EK, &params, &result);
        if (err == MWEB_ERR_INVALID_PRESIGN_SCALAR) {
            PASS("OVERFLOW_EK_REJECTED");
        } else {
            FAIL("OVERFLOW_EK_REJECTED", "expected INVALID_PRESIGN_SCALAR, got %d", err);
        }
    }

    /* 17. Fee feature bit set but has_fee=false → MWEB_ERR_KERNEL_FEATURE_MISMATCH */
    {
        static const uint8_t EK[32] = {0x01};
        static const uint8_t ZERO[32] = {0};
        mweb_input_ctx_t inp = { .value = 0 };
        struct mweb_kernel_sign_params params;
        memset(&params, 0, sizeof(params));
        params.inputs = &inp; params.n_inputs = 1;
        params.n_outputs = 0;
        params.features = MWEB_KERNEL_FEE_BIT;
        params.has_fee = false;
        params.received_tx_offset = ZERO;
        params.received_stealth_offset = ZERO;

        struct mweb_kernel_sign_outputs result;
        mweb_err_t err = mweb_sign_kernel_with_ek(EK, &params, &result);
        if (err == MWEB_ERR_KERNEL_FEATURE_MISMATCH) {
            PASS("FEE_BIT_NO_FEE_REJECTED");
        } else {
            FAIL("FEE_BIT_NO_FEE_REJECTED", "expected FEATURE_MISMATCH, got %d", err);
        }
    }

    /* 18. has_fee=true but no fee bit → MWEB_ERR_KERNEL_FEATURE_MISMATCH */
    {
        static const uint8_t EK[32] = {0x01};
        static const uint8_t ZERO[32] = {0};
        mweb_input_ctx_t inp = { .value = 0 };
        struct mweb_kernel_sign_params params;
        memset(&params, 0, sizeof(params));
        params.inputs = &inp; params.n_inputs = 1;
        params.n_outputs = 0;
        params.features = 0;  /* no fee bit */
        params.fee = 1000;
        params.has_fee = true;
        params.received_tx_offset = ZERO;
        params.received_stealth_offset = ZERO;

        struct mweb_kernel_sign_outputs result;
        mweb_err_t err = mweb_sign_kernel_with_ek(EK, &params, &result);
        if (err == MWEB_ERR_KERNEL_FEATURE_MISMATCH) {
            PASS("FEE_NO_BIT_REJECTED");
        } else {
            FAIL("FEE_NO_BIT_REJECTED", "expected FEATURE_MISMATCH, got %d", err);
        }
    }

    /* 19. Stealth bit set but stealth_key NULL → MWEB_ERR_MISSING_STEALTH_KEY */
    {
        static const uint8_t EK[32] = {0x01};
        static const uint8_t ZERO[32] = {0};
        mweb_input_ctx_t inp = { .value = 0 };
        struct mweb_kernel_sign_params params;
        memset(&params, 0, sizeof(params));
        params.inputs = &inp; params.n_inputs = 1;
        params.n_outputs = 0;
        params.features = MWEB_KERNEL_STEALTH_EXCESS_BIT;
        params.stealth_key_or_null = NULL;
        params.received_tx_offset = ZERO;
        params.received_stealth_offset = ZERO;

        struct mweb_kernel_sign_outputs result;
        mweb_err_t err = mweb_sign_kernel_with_ek(EK, &params, &result);
        if (err == MWEB_ERR_MISSING_STEALTH_KEY) {
            PASS("STEALTH_BIT_NO_KEY_REJECTED");
        } else {
            FAIL("STEALTH_BIT_NO_KEY_REJECTED", "expected MISSING_STEALTH_KEY, got %d", err);
        }
    }

    /* 20. stealth_key present but no stealth bit → MWEB_ERR_KERNEL_FEATURE_MISMATCH */
    {
        static const uint8_t EK[32] = {0x01};
        static const uint8_t ZERO[32] = {0};
        static const uint8_t SK[32] = {0x02};
        mweb_input_ctx_t inp = { .value = 0 };
        struct mweb_kernel_sign_params params;
        memset(&params, 0, sizeof(params));
        params.inputs = &inp; params.n_inputs = 1;
        params.n_outputs = 0;
        params.features = 0;  /* no stealth bit */
        params.stealth_key_or_null = SK;
        params.received_tx_offset = ZERO;
        params.received_stealth_offset = ZERO;

        struct mweb_kernel_sign_outputs result;
        mweb_err_t err = mweb_sign_kernel_with_ek(EK, &params, &result);
        if (err == MWEB_ERR_KERNEL_FEATURE_MISMATCH) {
            PASS("NO_BIT_STEALTH_KEY_REJECTED");
        } else {
            FAIL("NO_BIT_STEALTH_KEY_REJECTED", "expected FEATURE_MISMATCH, got %d", err);
        }
    }

    /* 21. Zero stealth_key → MWEB_ERR_INVALID_PRESIGN_SCALAR */
    {
        static const uint8_t EK[32] = {0x01};
        static const uint8_t ZERO[32] = {0};
        static const uint8_t ZERO_SK[32] = {0};
        mweb_input_ctx_t inp = { .value = 0 };
        struct mweb_kernel_sign_params params;
        memset(&params, 0, sizeof(params));
        params.inputs = &inp; params.n_inputs = 1;
        params.n_outputs = 0;
        params.features = MWEB_KERNEL_STEALTH_EXCESS_BIT;
        params.stealth_key_or_null = ZERO_SK;
        params.received_tx_offset = ZERO;
        params.received_stealth_offset = ZERO;

        struct mweb_kernel_sign_outputs result;
        mweb_err_t err = mweb_sign_kernel_with_ek(EK, &params, &result);
        if (err == MWEB_ERR_INVALID_PRESIGN_SCALAR) {
            PASS("ZERO_STEALTH_KEY_REJECTED");
        } else {
            FAIL("ZERO_STEALTH_KEY_REJECTED", "expected INVALID_PRESIGN_SCALAR, got %d", err);
        }
    }

    /* 22. Fee=0 with FeeBit accepted (presence-not-nonzero semantics) */
    {
        static const uint8_t EK[32] = {0x01};
        static const uint8_t ZERO[32] = {0};
        struct mweb_kernel_sign_params params;
        memset(&params, 0, sizeof(params));
        params.n_inputs = 0;
        params.n_outputs = 0;
        params.features = MWEB_KERNEL_FEE_BIT;
        params.fee = 0;
        params.has_fee = true;
        params.received_tx_offset = ZERO;
        params.received_stealth_offset = ZERO;

        struct mweb_kernel_sign_outputs result;
        mweb_err_t err = mweb_sign_kernel_with_ek(EK, &params, &result);
        if (err == MWEB_OK) {
            PASS("FEE_ZERO_ACCEPTED");
        } else {
            FAIL("FEE_ZERO_ACCEPTED", "expected OK, got %d", err);
        }
    }

    /* 23. Pegin bit set but has_pegin_amount=false → MWEB_ERR_KERNEL_FEATURE_MISMATCH */
    {
        static const uint8_t EK[32] = {0x01};
        static const uint8_t ZERO[32] = {0};
        struct mweb_kernel_sign_params params;
        memset(&params, 0, sizeof(params));
        params.features = MWEB_KERNEL_PEGIN_BIT;
        params.has_pegin_amount = false;
        params.received_tx_offset = ZERO;
        params.received_stealth_offset = ZERO;

        struct mweb_kernel_sign_outputs result;
        mweb_err_t err = mweb_sign_kernel_with_ek(EK, &params, &result);
        if (err == MWEB_ERR_KERNEL_FEATURE_MISMATCH) {
            PASS("PEGIN_BIT_MISMATCH");
        } else {
            FAIL("PEGIN_BIT_MISMATCH", "expected FEATURE_MISMATCH, got %d", err);
        }
    }

    /* 24. Pegout bit set but pegouts NULL → MWEB_ERR_KERNEL_FEATURE_MISMATCH */
    {
        static const uint8_t EK[32] = {0x01};
        static const uint8_t ZERO[32] = {0};
        struct mweb_kernel_sign_params params;
        memset(&params, 0, sizeof(params));
        params.features = MWEB_KERNEL_PEGOUT_BIT;
        params.pegouts = NULL;
        params.received_tx_offset = ZERO;
        params.received_stealth_offset = ZERO;

        struct mweb_kernel_sign_outputs result;
        mweb_err_t err = mweb_sign_kernel_with_ek(EK, &params, &result);
        if (err == MWEB_ERR_KERNEL_FEATURE_MISMATCH) {
            PASS("PEGOUT_BIT_NULL_MAP");
        } else {
            FAIL("PEGOUT_BIT_NULL_MAP", "expected FEATURE_MISMATCH, got %d", err);
        }
    }

    /* 25. Lock height bit set but has_lock_height=false → MWEB_ERR_KERNEL_FEATURE_MISMATCH */
    {
        static const uint8_t EK[32] = {0x01};
        static const uint8_t ZERO[32] = {0};
        struct mweb_kernel_sign_params params;
        memset(&params, 0, sizeof(params));
        params.features = MWEB_KERNEL_HEIGHT_LOCK_BIT;
        params.has_lock_height = false;
        params.received_tx_offset = ZERO;
        params.received_stealth_offset = ZERO;

        struct mweb_kernel_sign_outputs result;
        mweb_err_t err = mweb_sign_kernel_with_ek(EK, &params, &result);
        if (err == MWEB_ERR_KERNEL_FEATURE_MISMATCH) {
            PASS("LOCKHT_BIT_MISMATCH");
        } else {
            FAIL("LOCKHT_BIT_MISMATCH", "expected FEATURE_MISMATCH, got %d", err);
        }
    }

    /* 26. Extra data bit set but no extra data → MWEB_ERR_KERNEL_FEATURE_MISMATCH */
    {
        static const uint8_t EK[32] = {0x01};
        static const uint8_t ZERO[32] = {0};
        struct mweb_kernel_sign_params params;
        memset(&params, 0, sizeof(params));
        params.features = MWEB_KERNEL_EXTRA_DATA_BIT;
        params.extra_data = NULL;
        params.extra_data_len = 0;
        params.received_tx_offset = ZERO;
        params.received_stealth_offset = ZERO;

        struct mweb_kernel_sign_outputs result;
        mweb_err_t err = mweb_sign_kernel_with_ek(EK, &params, &result);
        if (err == MWEB_ERR_KERNEL_FEATURE_MISMATCH) {
            PASS("EXTRA_BIT_NO_DATA");
        } else {
            FAIL("EXTRA_BIT_NO_DATA", "expected FEATURE_MISMATCH, got %d", err);
        }
    }

    /* 27. mweb_validate_scalar: n-1 accepted, 1 accepted */
    {
        static const uint8_t N_MINUS_1[32] = {
            0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,
            0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFE,
            0xBA,0xAE,0xDC,0xE6,0xAF,0x48,0xA0,0x3B,
            0xBF,0xD2,0x5E,0x8C,0xD0,0x36,0x41,0x40,
        };
        static const uint8_t ONE[32] = {
            0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
            0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,
        };
        static const uint8_t ZERO[32] = {0};
        static const uint8_t ORDER[32] = {
            0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,
            0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFE,
            0xBA,0xAE,0xDC,0xE6,0xAF,0x48,0xA0,0x3B,
            0xBF,0xD2,0x5E,0x8C,0xD0,0x36,0x41,0x41,
        };

        bool ok = true;
        if (!mweb_validate_scalar(N_MINUS_1)) { ok = false; }
        if (!mweb_validate_scalar(ONE))        { ok = false; }
        if (mweb_validate_scalar(ZERO))        { ok = false; }
        if (mweb_validate_scalar(ORDER))       { ok = false; }
        if (ok) {
            PASS("VALIDATE_SCALAR");
        } else {
            FAIL("VALIDATE_SCALAR", "unexpected result");
        }
    }

    /* 28. NULL received_tx_offset → MWEB_ERR_INTERNAL */
    {
        static const uint8_t EK[32] = {0x01};
        static const uint8_t ZERO[32] = {0};
        struct mweb_kernel_sign_params params;
        memset(&params, 0, sizeof(params));
        params.features = MWEB_KERNEL_FEE_BIT;
        params.fee = 0; params.has_fee = true;
        params.received_tx_offset = NULL;
        params.received_stealth_offset = ZERO;

        struct mweb_kernel_sign_outputs result;
        mweb_err_t err = mweb_sign_kernel_with_ek(EK, &params, &result);
        if (err == MWEB_ERR_INTERNAL) {
            PASS("NULL_TX_OFFSET_REJECTED");
        } else {
            FAIL("NULL_TX_OFFSET_REJECTED", "expected INTERNAL, got %d", err);
        }
    }

    /* 29. NULL received_stealth_offset → MWEB_ERR_INTERNAL */
    {
        static const uint8_t EK[32] = {0x01};
        static const uint8_t ZERO[32] = {0};
        struct mweb_kernel_sign_params params;
        memset(&params, 0, sizeof(params));
        params.features = MWEB_KERNEL_FEE_BIT;
        params.fee = 0; params.has_fee = true;
        params.received_tx_offset = ZERO;
        params.received_stealth_offset = NULL;

        struct mweb_kernel_sign_outputs result;
        mweb_err_t err = mweb_sign_kernel_with_ek(EK, &params, &result);
        if (err == MWEB_ERR_INTERNAL) {
            PASS("NULL_STEALTH_OFFSET_REJECTED");
        } else {
            FAIL("NULL_STEALTH_OFFSET_REJECTED", "expected INTERNAL, got %d", err);
        }
    }

    /* 30. n_inputs > 0 but inputs NULL → MWEB_ERR_INTERNAL */
    {
        static const uint8_t EK[32] = {0x01};
        static const uint8_t ZERO[32] = {0};
        struct mweb_kernel_sign_params params;
        memset(&params, 0, sizeof(params));
        params.inputs = NULL; params.n_inputs = 1;
        params.features = MWEB_KERNEL_FEE_BIT;
        params.fee = 0; params.has_fee = true;
        params.received_tx_offset = ZERO;
        params.received_stealth_offset = ZERO;

        struct mweb_kernel_sign_outputs result;
        mweb_err_t err = mweb_sign_kernel_with_ek(EK, &params, &result);
        if (err == MWEB_ERR_INTERNAL) {
            PASS("NULL_INPUTS_REJECTED");
        } else {
            FAIL("NULL_INPUTS_REJECTED", "expected INTERNAL, got %d", err);
        }
    }

    /* 31. n_outputs > 0 but outputs NULL → MWEB_ERR_INTERNAL */
    {
        static const uint8_t EK[32] = {0x01};
        static const uint8_t ZERO[32] = {0};
        struct mweb_kernel_sign_params params;
        memset(&params, 0, sizeof(params));
        params.outputs = NULL; params.n_outputs = 1;
        params.features = MWEB_KERNEL_FEE_BIT;
        params.fee = 0; params.has_fee = true;
        params.received_tx_offset = ZERO;
        params.received_stealth_offset = ZERO;

        struct mweb_kernel_sign_outputs result;
        mweb_err_t err = mweb_sign_kernel_with_ek(EK, &params, &result);
        if (err == MWEB_ERR_INTERNAL) {
            PASS("NULL_OUTPUTS_REJECTED");
        } else {
            FAIL("NULL_OUTPUTS_REJECTED", "expected INTERNAL, got %d", err);
        }
    }

    /* 32. mweb_scalar_neg_mod_n handles non-canonical operand (a >= n) */
    {
        /* n + 1 should negate to n - 1 */
        static const uint8_t N_PLUS_1[32] = {
            0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,
            0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFE,
            0xBA,0xAE,0xDC,0xE6,0xAF,0x48,0xA0,0x3B,
            0xBF,0xD2,0x5E,0x8C,0xD0,0x36,0x41,0x42,
        };
        static const uint8_t EXPECTED_NEG[32] = {
            0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,
            0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFE,
            0xBA,0xAE,0xDC,0xE6,0xAF,0x48,0xA0,0x3B,
            0xBF,0xD2,0x5E,0x8C,0xD0,0x36,0x41,0x40,
        };
        uint8_t neg_out[32];
        if (!mweb_scalar_neg_mod_n(N_PLUS_1, neg_out)) {
            FAIL("NEG_NON_CANONICAL", "neg returned false");
        } else if (memcmp(neg_out, EXPECTED_NEG, 32) != 0) {
            FAIL("NEG_NON_CANONICAL", "wrong result");
            printf("  got:  ");
            for (int i = 0; i < 32; i++) printf("%02x", neg_out[i]);
            printf("\n  want: ");
            for (int i = 0; i < 32; i++) printf("%02x", EXPECTED_NEG[i]);
            printf("\n");
        } else {
            PASS("NEG_NON_CANONICAL");
        }
    }

    printf("\nmweb_kernel: %d tests, %d failures\n", test_count, failures);
    return failures;
}
