/*
 * Test vectors for mweb_kernel_sig_hash.
 *
 * Vectors generated by calling ltcsuite's MwebKernel.MessageHash()
 * with known inputs.
 */
#include "mweb_kernel.h"
#include "fixtures/kernel_hash_vectors.h"

#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#include <wally_core.h>
#include <wally_map.h>

static int failures = 0;
static int test_count = 0;

#define PASS(name) do { test_count++; printf("PASS: %s\n", name); } while (0)
#define FAIL(name, ...) do { test_count++; failures++; printf("FAIL: %s — ", name); printf(__VA_ARGS__); printf("\n"); } while (0)

static void check_hash(const char *name,
                        uint8_t features,
                        const uint8_t excess[33],
                        uint64_t fee, bool has_fee,
                        uint64_t pegin, bool has_pegin,
                        const struct wally_map *pegouts,
                        uint32_t lock_ht, bool has_lock_ht,
                        const uint8_t *stealth,
                        const uint8_t *extra, size_t extra_len,
                        const uint8_t expected[32])
{
    uint8_t got[32];
    if (!mweb_kernel_sig_hash(features, excess,
                              fee, has_fee,
                              pegin, has_pegin,
                              pegouts,
                              lock_ht, has_lock_ht,
                              stealth, extra, extra_len,
                              got)) {
        FAIL(name, "mweb_kernel_sig_hash returned false");
        return;
    }
    if (memcmp(got, expected, 32) != 0) {
        FAIL(name, "hash mismatch");
        printf("  got:  ");
        for (int i = 0; i < 32; i++) printf("%02x", got[i]);
        printf("\n  want: ");
        for (int i = 0; i < 32; i++) printf("%02x", expected[i]);
        printf("\n");
        return;
    }
    PASS(name);
}

/* Build a pegout map value for PSBT:
 * le64(amount) || compact_size(script_len) || script_bytes */
static uint8_t *build_pegout_value(uint64_t amount,
                                    const uint8_t *script, size_t script_len,
                                    size_t *out_len)
{
    uint8_t vi[9];
    size_t vi_len;

    /* le64 amount (8 bytes) */
    uint8_t amt_le[8];
    for (int i = 0; i < 8; i++) amt_le[i] = (uint8_t)(amount >> (i * 8));

    /* compact-size script_len */
    if (script_len < 0xfd) {
        vi[0] = (uint8_t)script_len;
        vi_len = 1;
    } else if (script_len <= 0xffff) {
        vi[0] = 0xfd;
        vi[1] = (uint8_t)(script_len);
        vi[2] = (uint8_t)(script_len >> 8);
        vi_len = 3;
    } else {
        vi[0] = 0xfe;
        vi[1] = (uint8_t)(script_len);
        vi[2] = (uint8_t)(script_len >> 8);
        vi[3] = (uint8_t)(script_len >> 16);
        vi[4] = (uint8_t)(script_len >> 24);
        vi_len = 5;
    }

    *out_len = 8 + vi_len + script_len;
    uint8_t *buf = malloc(*out_len);
    memcpy(buf, amt_le, 8);
    memcpy(buf + 8, vi, vi_len);
    memcpy(buf + 8 + vi_len, script, script_len);
    return buf;
}

static const uint8_t EXCESS[33] = {
    0x08,
    0xa1, 0xa1, 0xa1, 0xa1, 0xa1, 0xa1, 0xa1, 0xa1,
    0xa1, 0xa1, 0xa1, 0xa1, 0xa1, 0xa1, 0xa1, 0xa1,
    0xa1, 0xa1, 0xa1, 0xa1, 0xa1, 0xa1, 0xa1, 0xa1,
    0xa1, 0xa1, 0xa1, 0xa1, 0xa1, 0xa1, 0xa1, 0xa1
};

static const uint8_t STEALTH_EXCESS[33] = {
    0x02,
    0xb2, 0xb2, 0xb2, 0xb2, 0xb2, 0xb2, 0xb2, 0xb2,
    0xb2, 0xb2, 0xb2, 0xb2, 0xb2, 0xb2, 0xb2, 0xb2,
    0xb2, 0xb2, 0xb2, 0xb2, 0xb2, 0xb2, 0xb2, 0xb2,
    0xb2, 0xb2, 0xb2, 0xb2, 0xb2, 0xb2, 0xb2, 0xb2
};

/* P2WPKH script: OP_0 OP_PUSH20 <20-byte hash> */
static const uint8_t PEGOUT_SCRIPT_1[] = {
    0x00, 0x14,
    0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3,
    0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3, 0xc3,
    0xc3, 0xc3, 0xc3, 0xc3
};

/* P2WPKH script for ALL_FEATURES vector pegout 0 */
static const uint8_t PEGOUT_SCRIPT_ALL_0[] = {
    0x00, 0x14,
    0xd4, 0xd4, 0xd4, 0xd4, 0xd4, 0xd4, 0xd4, 0xd4,
    0xd4, 0xd4, 0xd4, 0xd4, 0xd4, 0xd4, 0xd4, 0xd4,
    0xd4, 0xd4, 0xd4, 0xd4
};

/* P2PKH script for ALL_FEATURES vector pegout 1 */
static const uint8_t PEGOUT_SCRIPT_ALL_1[] = {
    0x76, 0xa9, 0x14,
    0xe5, 0xe5, 0xe5, 0xe5, 0xe5, 0xe5, 0xe5, 0xe5,
    0xe5, 0xe5, 0xe5, 0xe5, 0xe5, 0xe5, 0xe5, 0xe5,
    0xe5, 0xe5, 0xe5, 0xe5,
    0x88, 0xac
};

static const uint8_t EXTRA_DATA[] = { 0xde, 0xad, 0xbe, 0xef };

int main(void)
{
    /* 1. FEE_ONLY: features=0x01, fee=50000 */
    check_hash("FEE_ONLY",
               MWEB_KERNEL_FEE_BIT, EXCESS,
               50000, true,
               0, false,
               NULL,
               0, false,
               NULL, NULL, 0,
               KERNEL_HASH_FEE_ONLY);

    /* 2. FEE_AND_PEGIN: features=0x03, fee=10000, pegin=100000000 */
    check_hash("FEE_AND_PEGIN",
               MWEB_KERNEL_FEE_BIT | MWEB_KERNEL_PEGIN_BIT, EXCESS,
               10000, true,
               100000000, true,
               NULL,
               0, false,
               NULL, NULL, 0,
               KERNEL_HASH_FEE_AND_PEGIN);

    /* 3. FEE_AND_STEALTH: features=0x11, fee=25000 */
    check_hash("FEE_AND_STEALTH",
               MWEB_KERNEL_FEE_BIT | MWEB_KERNEL_STEALTH_EXCESS_BIT, EXCESS,
               25000, true,
               0, false,
               NULL,
               0, false,
               STEALTH_EXCESS, NULL, 0,
               KERNEL_HASH_FEE_AND_STEALTH);

    /* 4. FEE_AND_LOCKHEIGHT: features=0x09, fee=30000, lock_height=800000 */
    check_hash("FEE_AND_LOCKHEIGHT",
               MWEB_KERNEL_FEE_BIT | MWEB_KERNEL_HEIGHT_LOCK_BIT, EXCESS,
               30000, true,
               0, false,
               NULL,
               800000, true,
               NULL, NULL, 0,
               KERNEL_HASH_FEE_AND_LOCKHEIGHT);

    /* 5. FEE_AND_PEGOUT: features=0x05, fee=40000, 1 pegout */
    {
        struct wally_map pegout_map;
        wally_map_init(1, NULL, &pegout_map);

        size_t pval_len;
        uint8_t *pval = build_pegout_value(200000000,
                                           PEGOUT_SCRIPT_1, sizeof(PEGOUT_SCRIPT_1),
                                           &pval_len);
        uint8_t key0 = 0x00;
        wally_map_add(&pegout_map, &key0, 1, pval, pval_len);
        free(pval);

        check_hash("FEE_AND_PEGOUT",
                   MWEB_KERNEL_FEE_BIT | MWEB_KERNEL_PEGOUT_BIT, EXCESS,
                   40000, true,
                   0, false,
                   &pegout_map,
                   0, false,
                   NULL, NULL, 0,
                   KERNEL_HASH_FEE_AND_PEGOUT);

        wally_map_clear(&pegout_map);
    }

    /* 6. ALL_FEATURES: features=0x3f, 2 pegouts, stealth, extra_data */
    {
        struct wally_map pegout_map;
        wally_map_init(2, NULL, &pegout_map);

        size_t pval0_len, pval1_len;
        uint8_t *pval0 = build_pegout_value(100000000,
                                            PEGOUT_SCRIPT_ALL_0, sizeof(PEGOUT_SCRIPT_ALL_0),
                                            &pval0_len);
        uint8_t *pval1 = build_pegout_value(50000000,
                                            PEGOUT_SCRIPT_ALL_1, sizeof(PEGOUT_SCRIPT_ALL_1),
                                            &pval1_len);
        uint8_t key0 = 0x00, key1 = 0x01;
        wally_map_add(&pegout_map, &key0, 1, pval0, pval0_len);
        wally_map_add(&pegout_map, &key1, 1, pval1, pval1_len);
        free(pval0);
        free(pval1);

        check_hash("ALL_FEATURES",
                   MWEB_KERNEL_ALL_BITS, EXCESS,
                   15000, true,
                   500000000, true,
                   &pegout_map,
                   900000, true,
                   STEALTH_EXCESS,
                   EXTRA_DATA, sizeof(EXTRA_DATA),
                   KERNEL_HASH_ALL_FEATURES);

        wally_map_clear(&pegout_map);
    }

    /* 7. FEE_ZERO: features=0x01, fee=0 (presence-not-nonzero) */
    check_hash("FEE_ZERO",
               MWEB_KERNEL_FEE_BIT, EXCESS,
               0, true,
               0, false,
               NULL,
               0, false,
               NULL, NULL, 0,
               KERNEL_HASH_FEE_ZERO);

    /* 8. EXTRA_DATA_EMPTY: features=0x21, fee=5000, extra_data=[] */
    check_hash("EXTRA_DATA_EMPTY",
               MWEB_KERNEL_FEE_BIT | MWEB_KERNEL_EXTRA_DATA_BIT, EXCESS,
               5000, true,
               0, false,
               NULL,
               0, false,
               NULL, NULL, 0,
               KERNEL_HASH_EXTRA_DATA_EMPTY);

    /* 9. PLAIN_NO_FEATURES: features=0x00 */
    check_hash("PLAIN_NO_FEATURES",
               0, EXCESS,
               0, false,
               0, false,
               NULL,
               0, false,
               NULL, NULL, 0,
               KERNEL_HASH_PLAIN_NO_FEATURES);

    /* 9. Negative: NULL excess_commitment → false */
    {
        uint8_t dummy[32];
        if (mweb_kernel_sig_hash(0x01, NULL,
                                 50000, true,
                                 0, false,
                                 NULL, 0, false,
                                 NULL, NULL, 0, dummy)) {
            FAIL("NULL_EXCESS", "should have returned false");
        } else {
            PASS("NULL_EXCESS rejected");
        }
    }

    printf("\nmweb_kernel: %d tests, %d failures\n", test_count, failures);
    return failures;
}
